### ISSUE TITLE
Notes May 30

### ISSUE THREAD

**Issue by dicook** [dicook/mulgar_book#14]
- [x] theme_minimal in Dim Red overview, and other chapters
- [x] Link to sec-dimension-reduction
- [x] Questions for Intro
- [x] Questions for Dim Red Overview: simulate normal with different VCs; sample data sets with outliers and non-linear
- [x] Questions for PCA: dobin exercise; additional small exercises where they have clear answers
- [x] Finish NLDR
- [x] Reference are in every section, seems like quarto bug
- [x] Numbering of chapters

**Comment by dicook** [comment]
- [x] I think the PCA chapter, for "model in the data space" should also have "data in the model space" plots, ie biplots.

**Comment by dicook** [comment]
- [x] PCA exercises need some draw the model in the data space exercises.

**Comment by uschiLaa** [comment]
Drawing the model only works with prcomp output, could we have a function that draws e.g. dobin model using the rotation matrix provided?

**Comment by dicook** [comment]
Sure!

**Comment by uschiLaa** [comment]
Drawing other models (e.g. dobin) postponed, everything else is done!
