### ISSUE TITLE
To Do: Jun 20

### ISSUE THREAD

**Issue by dicook** [dicook/mulgar_book#29]
- [x] Check hierfly, edges are mismatching now
- [x] Expand the risk example, perhaps into a project in the summarising results, to show what happens if your data doesn't have natural clusters.
- [x] Check correlation distance notation, at least use T instead of '. Report the numbers for the means
- [x] Remove the plotly spin and brush example.
- [x] Maybe add some words on the spin-and-brush to refer to connected clusters
- [x] More explanation of why looking at the dendrogram in high-d is helpful - could be explained on the 2D example first.

**Comment by dicook** [comment]
Use ^\top for transpose - should check this in other places.

**Comment by uschiLaa** [comment]
Maybe have subsections in the clustering chapter point to the project exercise using the risk in the final section, as a place to practice more?
