### ISSUE TITLE
To Do: Jul 18

### ISSUE THREAD

**Issue by dicook** [dicook/mulgar_book#35]
- [x] SOM: linking between map view and tour view with wireframe map
- [x] groupxy tour for comparing cluster solutions

**Comment by uschiLaa** [comment]
I tried a few things with groupxy but it seems not a great option in complex settings, might work well with smaller data though!

**Comment by dicook** [comment]
In the short-term it could be done using this approach:

1. Save tour path
2. Render both with plotly 
3. Embed in a document, like figure 8.7

In the future we modify the groupxy tour to allow for comparison of cluster solutions.

**Comment by uschiLaa** [comment]
It does work (except for drawing edges which seems off), but comparing clustering solutions with five or more groups in each solution is difficult to follow in a tour. Maybe selecting one or two clusters to highlight and compare will be the best option, but interactive control of plotly will probably help as well.
